// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBpT67GH_MtpwxNb1jmlECiiZ6Tv4ovwr8',
    appId: '1:221605114829:web:45b48aac8e93298dd80a84',
    messagingSenderId: '221605114829',
    projectId: 'virtuallearningapp-bbc01',
    authDomain: 'virtuallearningapp-bbc01.firebaseapp.com',
    storageBucket: 'virtuallearningapp-bbc01.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCaLACLiBFPjUO-X1AyinYWFS5FpOAT7kQ',
    appId: '1:221605114829:android:304bc984a021f16cd80a84',
    messagingSenderId: '221605114829',
    projectId: 'virtuallearningapp-bbc01',
    storageBucket: 'virtuallearningapp-bbc01.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCmdypyPGFAvGhf6QVUah9MSgNU-fYq8WM',
    appId: '1:221605114829:ios:26d413213427d866d80a84',
    messagingSenderId: '221605114829',
    projectId: 'virtuallearningapp-bbc01',
    storageBucket: 'virtuallearningapp-bbc01.appspot.com',
    iosBundleId: 'com.example.virtuallearningapp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCmdypyPGFAvGhf6QVUah9MSgNU-fYq8WM',
    appId: '1:221605114829:ios:26d413213427d866d80a84',
    messagingSenderId: '221605114829',
    projectId: 'virtuallearningapp-bbc01',
    storageBucket: 'virtuallearningapp-bbc01.appspot.com',
    iosBundleId: 'com.example.virtuallearningapp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBpT67GH_MtpwxNb1jmlECiiZ6Tv4ovwr8',
    appId: '1:221605114829:web:b2b403f0defc95ced80a84',
    messagingSenderId: '221605114829',
    projectId: 'virtuallearningapp-bbc01',
    authDomain: 'virtuallearningapp-bbc01.firebaseapp.com',
    storageBucket: 'virtuallearningapp-bbc01.appspot.com',
  );

}